logging:
  file:
    name: /logs/sboard.log
  level:
    jdbc:
      resultsettable: debug
      sqlonly: debug
      sqltiming: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        sql: debug
    root: info

server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: board_test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_test
    username: root
    password: "asd1234"
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  thymeleaf:
    prefix: classpath:/templates
